### ISSUE TITLE
Prior Art

### ISSUE THREAD

**Issue by chriscoyier** [davatron5000/deCSS3#11]
Totally not anywhere near as comprehensive, but just to give credit where it's due, this is oldest one I've seen: http://intridea.com/2010/4/12/toggle-css3-bookmarklet?blog=company

**Comment by chriscoyier** [comment]
closing, not really an issue, just wanted to note it somewhere.

**Comment by davatron5000** [comment]
Nice note! Actually it's worth probably putting on the readme or something somewhere.  And of course yours:

https://github.com/chriscoyier/CSS3-StripTease

**Comment by SlexAxton** [comment]
It is nice to learn what they removed, 
- border-radius
- box-shadow
- text-shadow
- border-image
- background-origin
- background-clip

and in the comments
- column-count
- column-width
- column-gap
- column-rule
- columns
- -webkit-box-reflect
- transform
- transition
- background-size
- word-wrap
- outline-offset

http://pastebin.com/qCMEpfJr
