### ISSUE TITLE
get security error in Firefox

### ISSUE THREAD

**Issue by ralyodio** [davatron5000/deCSS3#20]
Security error
[Break On This Error] if ( ! stylesheet.cssRules ) { 

deCSS3...6324741 (line 105)

I dragged the bookmark to my toolbar in Firefox 9 and clicked it, result was the above error.

the site is behind a firewall if that makes any difference.

**Comment by davatron5000** [comment]
Yup. This doesn't work in Firefox. Put a note on the homepage under [Currently Supports](http://davatron5000.github.com/deCSS3/).

**Comment by ralyodio** [comment]
I must have missed that. thanks.
