### ISSUE TITLE
License Type?

### ISSUE THREAD

**Issue by ghost** [davatron5000/deCSS3#21]

**Comment by SlexAxton** [comment]
We'd probably have to ask @davatron5000 - but I'm cool with WTFPL.

**Comment by davatron5000** [comment]
I'm more curious why @the-archer is going around asking everyone about their licenses. But suuuure. WTFPL. Let's do it.

**Comment by SlexAxton** [comment]
For symmetry: https://github.com/the-archer/boombabo/issues/1

**Comment by ghost** [comment]
@SlexAxton @davatron5000 Now that's the real issue, isn't it :P?  Why do I go around asking people about the licenses of their projects?

I just blog and need to classified things according to their licenses.

Shameless Plug: Feel free to subscribe http://goo.gl/qTvdO :-)
