### ISSUE TITLE
Firefox/Opera Security Error

### ISSUE THREAD

**Issue by davatron5000** [davatron5000/deCSS3#3]
deCSS3 won't work on Firefox due to the inability to access `document.styleSheets[i].cssRules` from a cross browser script.  this is a bit of a bummer.  Hopefully there's a workaround.

**Comment by SlexAxton** [comment]
I doubt there's a workaround. If there is, then it's a security hole that they'd patch. Our best bet is to see if there's a way to whitelist a site, I'd imagine.

For the record (at least new versions of) Chrome give you an "Insecure Script" warning, and make you press 'load anyway' in order to run it. (from my experience at least)

**Comment by davatron5000** [comment]
Re: Chrome - Maybe that's an http/https issue?

Re: Gecko - I was afraid of that. In all my Googlings, they consider a pretty insecure thing to read/edit cross domain cssRules. And they may be right. They know more than me. Maybe browser extensions is the win there?

I'll downgrade this thread from "Critical" to "Hopeless".

**Comment by chriscoyier** [comment]
Is a way to fix to inject all the JS not just a link to the JS? Sucks for updating purposes though...

**Comment by SlexAxton** [comment]
I think that might solve some issues, but the core is if the css is hosted somewhere else:

``` html
<link href="http://otherdomain.com/css.css" />
```

that will go blammo

**Comment by chriscoyier** [comment]
Also inline &lt;style> ?

**Comment by SlexAxton** [comment]
Inline styles are a bit of a mystery to me at this point.

**Comment by SlexAxton** [comment]
In our loop we could always add in dom elements with an inline style

``` javascript
   document.querySelectorAll('[style]')
```

then loop through and rewrite the style attribute the same way we're rewriting the cssRules. Toggling maybe a little more tricky, but I think I could do it.
